spark:
  appName: airflow-worker-dag-execution-basic-analytics
  master: local[*]
  checkpointLocation: file:///spark/checkpoints
  shuffle.partitions: 1
  consoleWriter: true
  outputMode: update

kafka:
  maxOffsetsPerTrigger: 100000
  bootstrap.servers: test1:9094
  startingOffsets: earliest
  topics:
    dlq: vagrant_out_deadletterqueue
    inputs:
      - vagrant_pro_eosdtv_lab5aobo_tst_heapp_airflow_worker_dag_execution_log_v1
    output: vagrant_out_eosdtv_lab5aobo_tst_heapp_airflow_worker_dag_execution_log_v1
  security.protocol: SASL_PLAINTEXT
  sasl.mechanism: PLAIN

analytics:
  componentName: vagrant.eosdtv.lab5aobo.tst.heapp.airflow.worker.dag.execution
  watermark: '1 minutes'
  window: '1 minutes'
